name: Lint Code Base

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Npm Install
        run: npm install
      - name: ESLint
        run: npx eslint /**/*.js
